internal_index = [
    {"name": "'M (glitch)", "type1": "Bird", "type2": "Normal"},
    {"name": "Rhydon", "type1": "Ground", "type2": "Rock"},
    {"name": "Kangaskhan", "type1": "Normal", "type2": ""},
    {"name": "Nidoran♂", "type1": "Poison", "type2": ""},
    {"name": "Clefairy", "type1": "Normal", "type2": ""},
    {"name": "Spearow", "type1": "Normal", "type2": "Flying"},
    {"name": "Voltorb", "type1": "Electric", "type2": ""},
    {"name": "Nidoking", "type1": "Poison", "type2": "Ground"},
    {"name": "Slowbro", "type1": "Water", "type2": "Psychic"},
    {"name": "Ivysaur", "type1": "Grass", "type2": "Poison"},
    {"name": "Exeggutor", "type1": "Grass", "type2": "Psychic"},
    {"name": "Lickitung", "type1": "Normal", "type2": ""},
    {"name": "Exeggcute", "type1": "Grass", "type2": "Psychic"},
    {"name": "Grimer", "type1": "Poison", "type2": ""},
    {"name": "Gengar", "type1": "Ghost", "type2": "Poison"},
    {"name": "Nidoran♀", "type1": "Poison", "type2": ""},
    {"name": "Nidoqueen", "type1": "Poison", "type2": "Ground"},
    {"name": "Cubone", "type1": "Ground", "type2": ""},
    {"name": "Rhyhorn", "type1": "Ground", "type2": "Rock"},
    {"name": "Lapras", "type1": "Water", "type2": "Ice"},
    {"name": "Arcanine", "type1": "Fire", "type2": ""},
    {"name": "Mew", "type1": "Psychic", "type2": ""},
    {"name": "Gyarados", "type1": "Water", "type2": "Flying"},
    {"name": "Shellder", "type1": "Water", "type2": ""},
    {"name": "Tentacool", "type1": "Water", "type2": "Poison"},
    {"name": "Gastly", "type1": "Ghost", "type2": "Poison"},
    {"name": "Scyther", "type1": "Bug", "type2": "Flying"},
    {"name": "Staryu", "type1": "Water", "type2": ""},
    {"name": "Blastoise", "type1": "Water", "type2": ""},
    {"name": "Pinsir", "type1": "Bug", "type2": ""},
    {"name": "Tangela", "type1": "Grass", "type2": ""},
    {"name": "MissingNo. (Gyaoon)", "type1": "Bird", "type2": "Normal"},
    {"name": "MissingNo. (Nidoran♂-like Pokémon)", "type1": "Bird", "type2": "Normal"},
    {"name": "Growlithe", "type1": "Fire", "type2": ""},
    {"name": "Onix", "type1": "Rock", "type2": "Ground"},
    {"name": "Fearow", "type1": "Normal", "type2": "Flying"},
    {"name": "Pidgey", "type1": "Normal", "type2": "Flying"},
    {"name": "Slowpoke", "type1": "Water", "type2": "Psychic"},
    {"name": "Kadabra", "type1": "Psychic", "type2": ""},
    {"name": "Graveler", "type1": "Rock", "type2": "Ground"},
    {"name": "Chansey", "type1": "Normal", "type2": ""},
    {"name": "Machoke", "type1": "Fighting", "type2": ""},
    {"name": "Mr. Mime", "type1": "Psychic", "type2": ""},
    {"name": "Hitmonlee", "type1": "Fighting", "type2": ""},
    {"name": "Hitmonchan", "type1": "Fighting", "type2": ""},
    {"name": "Arbok", "type1": "Poison", "type2": ""},
    {"name": "Parasect", "type1": "Bug", "type2": "Grass"},
    {"name": "Psyduck", "type1": "Water", "type2": ""},
    {"name": "Drowzee", "type1": "Psychic", "type2": ""},
    {"name": "Golem", "type1": "Rock", "type2": "Ground"},
    {"name": "MissingNo. (Balloonda)", "type1": "Bird", "type2": "Normal"},
    {"name": "Magmar", "type1": "Fire", "type2": ""},
    {"name": "MissingNo. (Buu)", "type1": "Bird", "type2": "Normal"},
    {"name": "Electabuzz", "type1": "Electric", "type2": ""},
    {"name": "Magneton", "type1": "Electric", "type2": ""},
    {"name": "Koffing", "type1": "Poison", "type2": ""},
    {"name": "MissingNo. (Deer)", "type1": "Bird", "type2": "Normal"},
    {"name": "Mankey", "type1": "Fighting", "type2": ""},
    {"name": "Seel", "type1": "Water", "type2": ""},
    {"name": "Diglett", "type1": "Ground", "type2": ""},
    {"name": "Tauros", "type1": "Normal", "type2": ""},
    {"name": "MissingNo.", "type1": "Bird", "type2": "Normal"},
    {"name": "MissingNo.", "type1": "Bird", "type2": "Normal"},
    {"name": "MissingNo.", "type1": "Bird", "type2": "Normal"},
    {"name": "Farfetch'd", "type1": "Normal", "type2": "Flying"},
    {"name": "Venonat", "type1": "Bug", "type2": "Poison"},
    {"name": "Dragonite", "type1": "Dragon", "type2": "Flying"},
    {"name": "MissingNo.", "type1": "Bird", "type2": "Normal"},
    {"name": "MissingNo.", "type1": "Bird", "type2": "Normal"},
    {"name": "MissingNo.", "type1": "Bird", "type2": "Normal"},
    {"name": "Doduo", "type1": "Normal", "type2": "Flying"},
    {"name": "Poliwag", "type1": "Water", "type2": ""},
    {"name": "Jynx", "type1": "Ice", "type2": "Psychic"},
    {"name": "Moltres", "type1": "Fire", "type2": "Flying"},
    {"name": "Articuno", "type1": "Ice", "type2": "Flying"},
    {"name": "Zapdos", "type1": "Electric", "type2": "Flying"},
    {"name": "Ditto", "type1": "Normal", "type2": ""},
    {"name": "Meowth", "type1": "Normal", "type2": ""},
    {"name": "Krabby", "type1": "Water", "type2": ""},
    {"name": "MissingNo.", "type1": "Bird", "type2": "Normal"},
    {"name": "MissingNo.", "type1": "Bird", "type2": "Normal"},
    {"name": "MissingNo.", "type1": "Bird", "type2": "Normal"},
    {"name": "Vulpix", "type1": "Fire", "type2": ""},
    {"name": "Ninetales", "type1": "Fire", "type2": ""},
    {"name": "Pikachu", "type1": "Electric", "type2": ""},
    {"name": "Raichu", "type1": "Electric", "type2": ""},
    {"name": "MissingNo.", "type1": "Bird", "type2": "Normal"},
    {"name": "MissingNo.", "type1": "Bird", "type2": "Normal"},
    {"name": "Dratini", "type1": "Dragon", "type2": ""},
    {"name": "Dragonair", "type1": "Dragon", "type2": ""},
    {"name": "Kabuto", "type1": "Rock", "type2": "Water"},
    {"name": "Kabutops", "type1": "Rock", "type2": "Water"},
    {"name": "Horsea", "type1": "Water", "type2": ""},
    {"name": "Seadra", "type1": "Water", "type2": ""},
    {"name": "MissingNo.", "type1": "Bird", "type2": "Normal"},
    {"name": "MissingNo.", "type1": "Bird", "type2": "Normal"},
    {"name": "Sandshrew", "type1": "Ground", "type2": ""},
    {"name": "Sandslash", "type1": "Ground", "type2": ""},
    {"name": "Omanyte", "type1": "Rock", "type2": "Water"},
    {"name": "Omastar", "type1": "Rock", "type2": "Water"},
    {"name": "Jigglypuff", "type1": "Normal", "type2": ""},
    {"name": "Wigglytuff", "type1": "Normal", "type2": ""},
    {"name": "Eevee", "type1": "Normal", "type2": ""},
    {"name": "Flareon", "type1": "Fire", "type2": ""},
    {"name": "Jolteon", "type1": "Electric", "type2": ""},
    {"name": "Vaporeon", "type1": "Water", "type2": ""},
    {"name": "Machop", "type1": "Fighting", "type2": ""},
    {"name": "Zubat", "type1": "Poison", "type2": "Flying"},
    {"name": "Ekans", "type1": "Poison", "type2": ""},
    {"name": "Paras", "type1": "Bug", "type2": "Grass"},
    {"name": "Poliwhirl", "type1": "Water", "type2": ""},
    {"name": "Poliwrath", "type1": "Water", "type2": "Fighting"},
    {"name": "Weedle", "type1": "Bug", "type2": "Poison"},
    {"name": "Kakuna", "type1": "Bug", "type2": "Poison"},
    {"name": "Beedrill", "type1": "Bug", "type2": "Poison"},
    {"name": "MissingNo.", "type1": "Bird", "type2": "Normal"},
    {"name": "Dodrio", "type1": "Normal", "type2": "Flying"},
    {"name": "Primeape", "type1": "Fighting", "type2": ""},
    {"name": "Dugtrio", "type1": "Ground", "type2": ""},
    {"name": "Venomoth", "type1": "Bug", "type2": "Poison"},
    {"name": "Dewgong", "type1": "Water", "type2": "Ice"},
    {"name": "MissingNo.", "type1": "Bird", "type2": "Normal"},
    {"name": "MissingNo. (Squid Pokémon 2)", "type1": "Bird", "type2": "Normal"},
    {"name": "Caterpie", "type1": "Bug", "type2": ""},
    {"name": "Metapod", "type1": "Bug", "type2": ""},
    {"name": "Butterfree", "type1": "Bug", "type2": "Flying"},
    {"name": "Machamp", "type1": "Fighting", "type2": ""},
    {"name": "MissingNo. (Golduck mid-evo)", "type1": "Bird", "type2": "Normal"},
    {"name": "Golduck", "type1": "Water", "type2": ""},
    {"name": "Hypno", "type1": "Psychic", "type2": ""},
    {"name": "Golbat", "type1": "Poison", "type2": "Flying"},
    {"name": "Mewtwo", "type1": "Psychic", "type2": ""},
    {"name": "Snorlax", "type1": "Normal", "type2": ""},
    {"name": "Magikarp", "type1": "Water", "type2": ""},
    {"name": "MissingNo. (Meowth pre-evo)", "type1": "Bird", "type2": "Normal"},
    {"name": "MissingNo.", "type1": "Bird", "type2": "Normal"},
    {"name": "Muk", "type1": "Poison", "type2": ""},
    {"name": "MissingNo. (Gyaoon pre-evo)", "type1": "Bird", "type2": "Normal"},
    {"name": "Kingler", "type1": "Water", "type2": ""},
    {"name": "Cloyster", "type1": "Water", "type2": "Ice"},
    {"name": "MissingNo. (Magneton-like Pokémon)", "type1": "Bird", "type2": "Normal"},
    {"name": "Electrode", "type1": "Electric", "type2": ""},
    {"name": "Clefable", "type1": "Normal", "type2": ""},
    {"name": "Weezing", "type1": "Poison", "type2": ""},
    {"name": "Persian", "type1": "Normal", "type2": ""},
    {"name": "Marowak", "type1": "Ground", "type2": ""},
    {"name": "MissingNo. (Marowak evo)", "type1": "Bird", "type2": "Normal"},
    {"name": "Haunter", "type1": "Ghost", "type2": "Poison"},
    {"name": "Abra", "type1": "Psychic", "type2": ""},
    {"name": "Alakazam", "type1": "Psychic", "type2": ""},
    {"name": "Pidgeotto", "type1": "Normal", "type2": "Flying"},
    {"name": "Pidgeot", "type1": "Normal", "type2": "Flying"},
    {"name": "Starmie", "type1": "Water", "type2": "Psychic"},
    {"name": "Bulbasaur", "type1": "Grass", "type2": "Poison"},
    {"name": "Venusaur", "type1": "Grass", "type2": "Poison"},
    {"name": "Tentacruel", "type1": "Water", "type2": "Poison"},
    {"name": "MissingNo. (Goldeen pre-evo)", "type1": "Bird", "type2": "Normal"},
    {"name": "Goldeen", "type1": "Water", "type2": ""},
    {"name": "Seaking", "type1": "Water", "type2": ""},
    {"name": "MissingNo. (Kotora)", "type1": "Bird", "type2": "Normal"},
    {"name": "MissingNo. (Raitora)", "type1": "Bird", "type2": "Normal"},
    {"name": "MissingNo. (Raitora evo)", "type1": "Bird", "type2": "Normal"},
    {"name": "MissingNo. (Ponyta pre-evo)", "type1": "Bird", "type2": "Normal"},
    {"name": "Ponyta", "type1": "Fire", "type2": ""},
    {"name": "Rapidash", "type1": "Fire", "type2": ""},
    {"name": "Rattata", "type1": "Normal", "type2": ""},
    {"name": "Raticate", "type1": "Normal", "type2": ""},
    {"name": "Nidorino", "type1": "Poison", "type2": ""},
    {"name": "Nidorina", "type1": "Poison", "type2": ""},
    {"name": "Geodude", "type1": "Rock", "type2": "Ground"},
    {"name": "Porygon", "type1": "Normal", "type2": ""},
    {"name": "Aerodactyl", "type1": "Rock", "type2": "Flying"},
    {"name": "MissingNo. (Blastoise-like Pokémon)", "type1": "Bird", "type2": "Normal"},
    {"name": "Magnemite", "type1": "Electric", "type2": ""},
    {"name": "MissingNo. (Lizard Pokémon 1)", "type1": "Bird", "type2": "Normal"},
    {"name": "MissingNo. (Gorochu)", "type1": "Bird", "type2": "Normal"},
    {"name": "Charmander", "type1": "Fire", "type2": ""},
    {"name": "Squirtle", "type1": "Water", "type2": ""},
    {"name": "Charmeleon", "type1": "Fire", "type2": ""},
    {"name": "Wartortle", "type1": "Water", "type2": ""},
    {"name": "Charizard", "type1": "Fire", "type2": "Flying"},
    {"name": "MissingNo. (Original Wartortle evo)", "type1": "Bird", "type2": "Normal"},
    {"name": "MissingNo. (Kabutops Fossil)", "type1": "Bird", "type2": "Normal"},
    {"name": "MissingNo. (Aerodactyl Fossil)", "type1": "Bird", "type2": "Normal"},
    {"name": "MissingNo. (Pokémon Tower Ghost)", "type1": "Bird", "type2": "Normal"},
    {"name": "Oddish", "type1": "Grass", "type2": "Poison"},
    {"name": "Gloom", "type1": "Grass", "type2": "Poison"},
    {"name": "Vileplume", "type1": "Grass", "type2": "Poison"},
    {"name": "Bellsprout", "type1": "Grass", "type2": "Poison"},
    {"name": "Weepinbell", "type1": "Grass", "type2": "Poison"},
    {"name": "Victreebel", "type1": "Grass", "type2": "Poison"}
]


#print(internal_index[45]["name"]+internal_index[45]["type1"]+internal_index[45]["type2"])

