#https://tcrf.net/Pok%C3%A9mon_Red_and_Blue/Internal_Index_Number
internal_index = [
    {"name": "'M (glitch)", "type1": "Bird", "type2": "Normal"},
    {"name": "Rhydon", "type1": "Ground", "type2": "Rock"},
    {"name": "Kangaskhan", "type1": "Normal", "type2": ""},
    {"name": "Nidoran♂", "type1": "Poison", "type2": ""},
    {"name": "Clefairy", "type1": "Normal", "type2": ""},
    {"name": "Spearow", "type1": "Normal", "type2": "Flying"},
    {"name": "Voltorb", "type1": "Electric", "type2": ""},
    {"name": "Nidoking", "type1": "Poison", "type2": "Ground"},
    {"name": "Slowbro", "type1": "Water", "type2": "Psychic"},
    {"name": "Ivysaur", "type1": "Grass", "type2": "Poison"},
    {"name": "Exeggutor", "type1": "Grass", "type2": "Psychic"},
    {"name": "Lickitung", "type1": "Normal", "type2": ""},
    {"name": "Exeggcute", "type1": "Grass", "type2": "Psychic"},
    {"name": "Grimer", "type1": "Poison", "type2": ""},
    {"name": "Gengar", "type1": "Ghost", "type2": "Poison"},
    {"name": "Nidoran♀", "type1": "Poison", "type2": ""},
    {"name": "Nidoqueen", "type1": "Poison", "type2": "Ground"},
    {"name": "Cubone", "type1": "Ground", "type2": ""},
    {"name": "Rhyhorn", "type1": "Ground", "type2": "Rock"},
    {"name": "Lapras", "type1": "Water", "type2": "Ice"},
    {"name": "Arcanine", "type1": "Fire", "type2": ""},
    {"name": "Mew", "type1": "Psychic", "type2": ""},
    {"name": "Gyarados", "type1": "Water", "type2": "Flying"},
    {"name": "Shellder", "type1": "Water", "type2": ""},
    {"name": "Tentacool", "type1": "Water", "type2": "Poison"},
    {"name": "Gastly", "type1": "Ghost", "type2": "Poison"},
    {"name": "Scyther", "type1": "Bug", "type2": "Flying"},
    {"name": "Staryu", "type1": "Water", "type2": ""},
    {"name": "Blastoise", "type1": "Water", "type2": ""},
    {"name": "Pinsir", "type1": "Bug", "type2": ""},
    {"name": "Tangela", "type1": "Grass", "type2": ""},
    {"name": "MissingNo. (Gyaoon)", "type1": "Bird", "type2": "Normal"},
    {"name": "MissingNo. (Nidoran♂-like Pokémon)", "type1": "Bird", "type2": "Normal"},
    {"name": "Growlithe", "type1": "Fire", "type2": ""},
    {"name": "Onix", "type1": "Rock", "type2": "Ground"},
    {"name": "Fearow", "type1": "Normal", "type2": "Flying"},
    {"name": "Pidgey", "type1": "Normal", "type2": "Flying"},
    {"name": "Slowpoke", "type1": "Water", "type2": "Psychic"},
    {"name": "Kadabra", "type1": "Psychic", "type2": ""},
    {"name": "Graveler", "type1": "Rock", "type2": "Ground"},
    {"name": "Chansey", "type1": "Normal", "type2": ""},
    {"name": "Machoke", "type1": "Fighting", "type2": ""},
    {"name": "Mr. Mime", "type1": "Psychic", "type2": ""},
    {"name": "Hitmonlee", "type1": "Fighting", "type2": ""},
    {"name": "Hitmonchan", "type1": "Fighting", "type2": ""},
    {"name": "Arbok", "type1": "Poison", "type2": ""},
    {"name": "Parasect", "type1": "Bug", "type2": "Grass"},
    {"name": "Psyduck", "type1": "Water", "type2": ""},
    {"name": "Drowzee", "type1": "Psychic", "type2": ""},
    {"name": "Golem", "type1": "Rock", "type2": "Ground"},
    {"name": "MissingNo. (Balloonda)", "type1": "Bird", "type2": "Normal"},
    {"name": "Magmar", "type1": "Fire", "type2": ""},
    {"name": "MissingNo. (Buu)", "type1": "Bird", "type2": "Normal"},
    {"name": "Electabuzz", "type1": "Electric", "type2": ""},
    {"name": "Magneton", "type1": "Electric", "type2": ""},
    {"name": "Koffing", "type1": "Poison", "type2": ""},
    {"name": "MissingNo. (Deer)", "type1": "Bird", "type2": "Normal"},
    {"name": "Mankey", "type1": "Fighting", "type2": ""},
    {"name": "Seel", "type1": "Water", "type2": ""},
    {"name": "Diglett", "type1": "Ground", "type2": ""},
    {"name": "Tauros", "type1": "Normal", "type2": ""},
    {"name": "MissingNo.", "type1": "Bird", "type2": "Normal"},
    {"name": "MissingNo.", "type1": "Bird", "type2": "Normal"},
    {"name": "MissingNo.", "type1": "Bird", "type2": "Normal"},
    {"name": "Farfetch'd", "type1": "Normal", "type2": "Flying"},
    {"name": "Venonat", "type1": "Bug", "type2": "Poison"},
    {"name": "Dragonite", "type1": "Dragon", "type2": "Flying"},
    {"name": "MissingNo.", "type1": "Bird", "type2": "Normal"},
    {"name": "MissingNo.", "type1": "Bird", "type2": "Normal"},
    {"name": "MissingNo.", "type1": "Bird", "type2": "Normal"},
    {"name": "Doduo", "type1": "Normal", "type2": "Flying"},
    {"name": "Poliwag", "type1": "Water", "type2": ""},
    {"name": "Jynx", "type1": "Ice", "type2": "Psychic"},
    {"name": "Moltres", "type1": "Fire", "type2": "Flying"},
    {"name": "Articuno", "type1": "Ice", "type2": "Flying"},
    {"name": "Zapdos", "type1": "Electric", "type2": "Flying"},
    {"name": "Ditto", "type1": "Normal", "type2": ""},
    {"name": "Meowth", "type1": "Normal", "type2": ""},
    {"name": "Krabby", "type1": "Water", "type2": ""},
    {"name": "MissingNo.", "type1": "Bird", "type2": "Normal"},
    {"name": "MissingNo.", "type1": "Bird", "type2": "Normal"},
    {"name": "MissingNo.", "type1": "Bird", "type2": "Normal"},
    {"name": "Vulpix", "type1": "Fire", "type2": ""},
    {"name": "Ninetales", "type1": "Fire", "type2": ""},
    {"name": "Pikachu", "type1": "Electric", "type2": ""},
    {"name": "Raichu", "type1": "Electric", "type2": ""},
    {"name": "MissingNo.", "type1": "Bird", "type2": "Normal"},
    {"name": "MissingNo.", "type1": "Bird", "type2": "Normal"},
    {"name": "Dratini", "type1": "Dragon", "type2": ""},
    {"name": "Dragonair", "type1": "Dragon", "type2": ""},
    {"name": "Kabuto", "type1": "Rock", "type2": "Water"},
    {"name": "Kabutops", "type1": "Rock", "type2": "Water"},
    {"name": "Horsea", "type1": "Water", "type2": ""},
    {"name": "Seadra", "type1": "Water", "type2": ""},
    {"name": "MissingNo.", "type1": "Bird", "type2": "Normal"},
    {"name": "MissingNo.", "type1": "Bird", "type2": "Normal"},
    {"name": "Sandshrew", "type1": "Ground", "type2": ""},
    {"name": "Sandslash", "type1": "Ground", "type2": ""},
    {"name": "Omanyte", "type1": "Rock", "type2": "Water"},
    {"name": "Omastar", "type1": "Rock", "type2": "Water"},
    {"name": "Jigglypuff", "type1": "Normal", "type2": ""},
    {"name": "Wigglytuff", "type1": "Normal", "type2": ""},
    {"name": "Eevee", "type1": "Normal", "type2": ""},
    {"name": "Flareon", "type1": "Fire", "type2": ""},
    {"name": "Jolteon", "type1": "Electric", "type2": ""},
    {"name": "Vaporeon", "type1": "Water", "type2": ""},
    {"name": "Machop", "type1": "Fighting", "type2": ""},
    {"name": "Zubat", "type1": "Poison", "type2": "Flying"},
    {"name": "Ekans", "type1": "Poison", "type2": ""},
    {"name": "Paras", "type1": "Bug", "type2": "Grass"},
    {"name": "Poliwhirl", "type1": "Water", "type2": ""},
    {"name": "Poliwrath", "type1": "Water", "type2": "Fighting"},
    {"name": "Weedle", "type1": "Bug", "type2": "Poison"},
    {"name": "Kakuna", "type1": "Bug", "type2": "Poison"},
    {"name": "Beedrill", "type1": "Bug", "type2": "Poison"},
    {"name": "MissingNo.", "type1": "Bird", "type2": "Normal"},
    {"name": "Dodrio", "type1": "Normal", "type2": "Flying"},
    {"name": "Primeape", "type1": "Fighting", "type2": ""},
    {"name": "Dugtrio", "type1": "Ground", "type2": ""},
    {"name": "Venomoth", "type1": "Bug", "type2": "Poison"},
    {"name": "Dewgong", "type1": "Water", "type2": "Ice"},
    {"name": "MissingNo.", "type1": "Bird", "type2": "Normal"},
    {"name": "MissingNo. (Squid Pokémon 2)", "type1": "Bird", "type2": "Normal"},
    {"name": "Caterpie", "type1": "Bug", "type2": ""},
    {"name": "Metapod", "type1": "Bug", "type2": ""},
    {"name": "Butterfree", "type1": "Bug", "type2": "Flying"},
    {"name": "Machamp", "type1": "Fighting", "type2": ""},
    {"name": "MissingNo. (Golduck mid-evo)", "type1": "Bird", "type2": "Normal"},
    {"name": "Golduck", "type1": "Water", "type2": ""},
    {"name": "Hypno", "type1": "Psychic", "type2": ""},
    {"name": "Golbat", "type1": "Poison", "type2": "Flying"},
    {"name": "Mewtwo", "type1": "Psychic", "type2": ""},
    {"name": "Snorlax", "type1": "Normal", "type2": ""},
    {"name": "Magikarp", "type1": "Water", "type2": ""},
    {"name": "MissingNo. (Meowth pre-evo)", "type1": "Bird", "type2": "Normal"},
    {"name": "MissingNo.", "type1": "Bird", "type2": "Normal"},
    {"name": "Muk", "type1": "Poison", "type2": ""},
    {"name": "MissingNo. (Gyaoon pre-evo)", "type1": "Bird", "type2": "Normal"},
    {"name": "Kingler", "type1": "Water", "type2": ""},
    {"name": "Cloyster", "type1": "Water", "type2": "Ice"},
    {"name": "MissingNo. (Magneton-like Pokémon)", "type1": "Bird", "type2": "Normal"},
    {"name": "Electrode", "type1": "Electric", "type2": ""},
    {"name": "Clefable", "type1": "Normal", "type2": ""},
    {"name": "Weezing", "type1": "Poison", "type2": ""},
    {"name": "Persian", "type1": "Normal", "type2": ""},
    {"name": "Marowak", "type1": "Ground", "type2": ""},
    {"name": "MissingNo. (Marowak evo)", "type1": "Bird", "type2": "Normal"},
    {"name": "Haunter", "type1": "Ghost", "type2": "Poison"},
    {"name": "Abra", "type1": "Psychic", "type2": ""},
    {"name": "Alakazam", "type1": "Psychic", "type2": ""},
    {"name": "Pidgeotto", "type1": "Normal", "type2": "Flying"},
    {"name": "Pidgeot", "type1": "Normal", "type2": "Flying"},
    {"name": "Starmie", "type1": "Water", "type2": "Psychic"},
    {"name": "Bulbasaur", "type1": "Grass", "type2": "Poison"},
    {"name": "Venusaur", "type1": "Grass", "type2": "Poison"},
    {"name": "Tentacruel", "type1": "Water", "type2": "Poison"},
    {"name": "MissingNo. (Goldeen pre-evo)", "type1": "Bird", "type2": "Normal"},
    {"name": "Goldeen", "type1": "Water", "type2": ""},
    {"name": "Seaking", "type1": "Water", "type2": ""},
    {"name": "MissingNo. (Kotora)", "type1": "Bird", "type2": "Normal"},
    {"name": "MissingNo. (Raitora)", "type1": "Bird", "type2": "Normal"},
    {"name": "MissingNo. (Raitora evo)", "type1": "Bird", "type2": "Normal"},
    {"name": "MissingNo. (Ponyta pre-evo)", "type1": "Bird", "type2": "Normal"},
    {"name": "Ponyta", "type1": "Fire", "type2": ""},
    {"name": "Rapidash", "type1": "Fire", "type2": ""},
    {"name": "Rattata", "type1": "Normal", "type2": ""},
    {"name": "Raticate", "type1": "Normal", "type2": ""},
    {"name": "Nidorino", "type1": "Poison", "type2": ""},
    {"name": "Nidorina", "type1": "Poison", "type2": ""},
    {"name": "Geodude", "type1": "Rock", "type2": "Ground"},
    {"name": "Porygon", "type1": "Normal", "type2": ""},
    {"name": "Aerodactyl", "type1": "Rock", "type2": "Flying"},
    {"name": "MissingNo. (Blastoise-like Pokémon)", "type1": "Bird", "type2": "Normal"},
    {"name": "Magnemite", "type1": "Electric", "type2": ""},
    {"name": "MissingNo. (Lizard Pokémon 1)", "type1": "Bird", "type2": "Normal"},
    {"name": "MissingNo. (Gorochu)", "type1": "Bird", "type2": "Normal"},
    {"name": "Charmander", "type1": "Fire", "type2": ""},
    {"name": "Squirtle", "type1": "Water", "type2": ""},
    {"name": "Charmeleon", "type1": "Fire", "type2": ""},
    {"name": "Wartortle", "type1": "Water", "type2": ""},
    {"name": "Charizard", "type1": "Fire", "type2": "Flying"},
    {"name": "MissingNo. (Original Wartortle evo)", "type1": "Bird", "type2": "Normal"},
    {"name": "MissingNo. (Kabutops Fossil)", "type1": "Bird", "type2": "Normal"},
    {"name": "MissingNo. (Aerodactyl Fossil)", "type1": "Bird", "type2": "Normal"},
    {"name": "MissingNo. (Pokémon Tower Ghost)", "type1": "Bird", "type2": "Normal"},
    {"name": "Oddish", "type1": "Grass", "type2": "Poison"},
    {"name": "Gloom", "type1": "Grass", "type2": "Poison"},
    {"name": "Vileplume", "type1": "Grass", "type2": "Poison"},
    {"name": "Bellsprout", "type1": "Grass", "type2": "Poison"},
    {"name": "Weepinbell", "type1": "Grass", "type2": "Poison"},
    {"name": "Victreebel", "type1": "Grass", "type2": "Poison"}
]


#print(internal_index[45]["name"]+internal_index[45]["type1"]+internal_index[45]["type2"])


move_index=[
  {},
  {"name":"Pound","type":"Normal"},
  {"name":"Karate Chop","type":"Fighting"},
  {"name":"Double Slap","type":"Normal"},
  {"name":"Comet Punch","type":"Normal"},
  {"name":"Mega Punch","type":"Normal"},
  {"name":"Pay Day","type":"Normal"},
  {"name":"Fire Punch","type":"Fire"},
  {"name":"Ice Punch","type":"Ice"},
  {"name":"Thunder Punch","type":"Electric"},
  {"name":"Scratch","type":"Normal"},
  {"name":"Vise Grip","type":"Normal"},
  {"name":"Guillotine","type":"Normal"},
  {"name":"Razor Wind","type":"Normal"},
  {"name":"Swords Dance","type":"Normal"},
  {"name":"Cut","type":"Normal"},
  {"name":"Gust","type":"Flying"},
  {"name":"Wing Attack","type":"Flying"},
  {"name":"Whirlwind","type":"Normal"},
  {"name":"Fly","type":"Flying"},
  {"name":"Bind","type":"Normal"},
  {"name":"Slam","type":"Normal"},
  {"name":"Vine Whip","type":"Grass"},
  {"name":"Stomp","type":"Normal"},
  {"name":"Double Kick","type":"Fighting"},
  {"name":"Mega Kick","type":"Normal"},
  {"name":"Jump Kick","type":"Fighting"},
  {"name":"Rolling Kick","type":"Fighting"},
  {"name":"Sand Attack","type":"Ground"},
  {"name":"Headbutt","type":"Normal"},
  {"name":"Horn Attack","type":"Normal"},
  {"name":"Fury Attack","type":"Normal"},
  {"name":"Horn Drill","type":"Normal"},
  {"name":"Tackle","type":"Normal"},
  {"name":"Body Slam","type":"Normal"},
  {"name":"Wrap","type":"Normal"},
  {"name":"Take Down","type":"Normal"},
  {"name":"Thrash","type":"Normal"},
  {"name":"Double-Edge","type":"Normal"},
  {"name":"Tail Whip","type":"Normal"},
  {"name":"Poison Sting","type":"Poison"},
  {"name":"Twineedle","type":"Bug"},
  {"name":"Pin Missile","type":"Bug"},
  {"name":"Leer","type":"Normal"},
  {"name":"Bite","type":"Dark"},
  {"name":"Growl","type":"Normal"},
  {"name":"Roar","type":"Normal"},
  {"name":"Sing","type":"Normal"},
  {"name":"Supersonic","type":"Normal"},
  {"name":"Sonic Boom","type":"Normal"},
  {"name":"Disable","type":"Normal"},
  {"name":"Acid","type":"Poison"},
  {"name":"Ember","type":"Fire"},
  {"name":"Flamethrower","type":"Fire"},
  {"name":"Mist","type":"Ice"},
  {"name":"Water Gun","type":"Water"},
  {"name":"Hydro Pump","type":"Water"},
  {"name":"Surf","type":"Water"},
  {"name":"Ice Beam","type":"Ice"},
  {"name":"Blizzard","type":"Ice"},
  {"name":"Psybeam","type":"Psychic"},
  {"name":"Bubble Beam","type":"Water"},
  {"name":"Aurora Beam","type":"Ice"},
  {"name":"Hyper Beam","type":"Normal"},
  {"name":"Peck","type":"Flying"},
  {"name":"Drill Peck","type":"Flying"},
  {"name":"Submission","type":"Fighting"},
  {"name":"Low Kick","type":"Fighting"},
  {"name":"Counter","type":"Fighting"},
  {"name":"Seismic Toss","type":"Fighting"},
  {"name":"Strength","type":"Normal"},
  {"name":"Absorb","type":"Grass"},
  {"name":"Mega Drain","type":"Grass"},
  {"name":"Leech Seed","type":"Grass"},
  {"name":"Growth","type":"Normal"},
  {"name":"Razor Leaf","type":"Grass"},
  {"name":"Solar Beam","type":"Grass"},
  {"name":"Poison Powder","type":"Poison"},
  {"name":"Stun Spore","type":"Grass"},
  {"name":"Sleep Powder","type":"Grass"},
  {"name":"Petal Dance","type":"Grass"},
  {"name":"String Shot","type":"Bug"},
  {"name":"Dragon Rage","type":"Dragon"},
  {"name":"Fire Spin","type":"Fire"},
  {"name":"Thunder Shock","type":"Electric"},
  {"name":"Thunderbolt","type":"Electric"},
  {"name":"Thunder Wave","type":"Electric"},
  {"name":"Thunder","type":"Electric"},
  {"name":"Rock Throw","type":"Rock"},
  {"name":"Earthquake","type":"Ground"},
  {"name":"Fissure","type":"Ground"},
  {"name":"Dig","type":"Ground"},
  {"name":"Toxic","type":"Poison"},
  {"name":"Confusion","type":"Psychic"},
  {"name":"Psychic","type":"Psychic"},
  {"name":"Hypnosis","type":"Psychic"},
  {"name":"Meditate","type":"Psychic"},
  {"name":"Agility","type":"Psychic"},
  {"name":"Quick Attack","type":"Normal"},
  {"name":"Rage","type":"Normal"},
  {"name":"Teleport","type":"Psychic"},
  {"name":"Night Shade","type":"Ghost"},
  {"name":"Mimic","type":"Normal"},
  {"name":"Screech","type":"Normal"},
  {"name":"Double Team","type":"Normal"},
  {"name":"Recover","type":"Normal"},
  {"name":"Harden","type":"Normal"},
  {"name":"Minimize","type":"Normal"},
  {"name":"Smokescreen","type":"Normal"},
  {"name":"Confuse Ray","type":"Ghost"},
  {"name":"Withdraw","type":"Water"},
  {"name":"Defense Curl","type":"Normal"},
  {"name":"Barrier","type":"Psychic"},
  {"name":"Light Screen","type":"Psychic"},
  {"name":"Haze","type":"Ice"},
  {"name":"Reflect","type":"Psychic"},
  {"name":"Focus Energy","type":"Normal"},
  {"name":"Bide","type":"Normal"},
  {"name":"Metronome","type":"Normal"},
  {"name":"Mirror Move","type":"Flying"},
  {"name":"Self-Destruct","type":"Normal"},
  {"name":"Egg Bomb","type":"Normal"},
  {"name":"Lick","type":"Ghost"},
  {"name":"Smog","type":"Poison"},
  {"name":"Sludge","type":"Poison"},
  {"name":"Bone Club","type":"Ground"},
  {"name":"Fire Blast","type":"Fire"},
  {"name":"Waterfall","type":"Water"},
  {"name":"Clamp","type":"Water"},
  {"name":"Swift","type":"Normal"},
  {"name":"Skull Bash","type":"Normal"},
  {"name":"Spike Cannon","type":"Normal"},
  {"name":"Constrict","type":"Normal"},
  {"name":"Amnesia","type":"Psychic"},
  {"name":"Kinesis","type":"Psychic"},
  {"name":"Soft-Boiled","type":"Normal"},
  {"name":"High Jump Kick","type":"Fighting"}
]