move_index=[
  {"name":"Pound","type":"Normal"},
  {"name":"Karate Chop","type":"Fighting"},
  {"name":"Double Slap","type":"Normal"},
  {"name":"Comet Punch","type":"Normal"},
  {"name":"Mega Punch","type":"Normal"},
  {"name":"Pay Day","type":"Normal"},
  {"name":"Fire Punch","type":"Fire"},
  {"name":"Ice Punch","type":"Ice"},
  {"name":"Thunder Punch","type":"Electric"},
  {"name":"Scratch","type":"Normal"},
  {"name":"Vise Grip","type":"Normal"},
  {"name":"Guillotine","type":"Normal"},
  {"name":"Razor Wind","type":"Normal"},
  {"name":"Swords Dance","type":"Normal"},
  {"name":"Cut","type":"Normal"},
  {"name":"Gust","type":"Flying"},
  {"name":"Wing Attack","type":"Flying"},
  {"name":"Whirlwind","type":"Normal"},
  {"name":"Fly","type":"Flying"},
  {"name":"Bind","type":"Normal"},
  {"name":"Slam","type":"Normal"},
  {"name":"Vine Whip","type":"Grass"},
  {"name":"Stomp","type":"Normal"},
  {"name":"Double Kick","type":"Fighting"},
  {"name":"Mega Kick","type":"Normal"},
  {"name":"Jump Kick","type":"Fighting"},
  {"name":"Rolling Kick","type":"Fighting"},
  {"name":"Sand Attack","type":"Ground"},
  {"name":"Headbutt","type":"Normal"},
  {"name":"Horn Attack","type":"Normal"},
  {"name":"Fury Attack","type":"Normal"},
  {"name":"Horn Drill","type":"Normal"},
  {"name":"Tackle","type":"Normal"},
  {"name":"Body Slam","type":"Normal"},
  {"name":"Wrap","type":"Normal"},
  {"name":"Take Down","type":"Normal"},
  {"name":"Thrash","type":"Normal"},
  {"name":"Double-Edge","type":"Normal"},
  {"name":"Tail Whip","type":"Normal"},
  {"name":"Poison Sting","type":"Poison"},
  {"name":"Twineedle","type":"Bug"},
  {"name":"Pin Missile","type":"Bug"},
  {"name":"Leer","type":"Normal"},
  {"name":"Bite","type":"Dark"},
  {"name":"Growl","type":"Normal"},
  {"name":"Roar","type":"Normal"},
  {"name":"Sing","type":"Normal"},
  {"name":"Supersonic","type":"Normal"},
  {"name":"Sonic Boom","type":"Normal"},
  {"name":"Disable","type":"Normal"},
  {"name":"Acid","type":"Poison"},
  {"name":"Ember","type":"Fire"},
  {"name":"Flamethrower","type":"Fire"},
  {"name":"Mist","type":"Ice"},
  {"name":"Water Gun","type":"Water"},
  {"name":"Hydro Pump","type":"Water"},
  {"name":"Surf","type":"Water"},
  {"name":"Ice Beam","type":"Ice"},
  {"name":"Blizzard","type":"Ice"},
  {"name":"Psybeam","type":"Psychic"},
  {"name":"Bubble Beam","type":"Water"},
  {"name":"Aurora Beam","type":"Ice"},
  {"name":"Hyper Beam","type":"Normal"},
  {"name":"Peck","type":"Flying"},
  {"name":"Drill Peck","type":"Flying"},
  {"name":"Submission","type":"Fighting"},
  {"name":"Low Kick","type":"Fighting"},
  {"name":"Counter","type":"Fighting"},
  {"name":"Seismic Toss","type":"Fighting"},
  {"name":"Strength","type":"Normal"},
  {"name":"Absorb","type":"Grass"},
  {"name":"Mega Drain","type":"Grass"},
  {"name":"Leech Seed","type":"Grass"},
  {"name":"Growth","type":"Normal"},
  {"name":"Razor Leaf","type":"Grass"},
  {"name":"Solar Beam","type":"Grass"},
  {"name":"Poison Powder","type":"Poison"},
  {"name":"Stun Spore","type":"Grass"},
  {"name":"Sleep Powder","type":"Grass"},
  {"name":"Petal Dance","type":"Grass"},
  {"name":"String Shot","type":"Bug"},
  {"name":"Dragon Rage","type":"Dragon"},
  {"name":"Fire Spin","type":"Fire"},
  {"name":"Thunder Shock","type":"Electric"},
  {"name":"Thunderbolt","type":"Electric"},
  {"name":"Thunder Wave","type":"Electric"},
  {"name":"Thunder","type":"Electric"},
  {"name":"Rock Throw","type":"Rock"},
  {"name":"Earthquake","type":"Ground"},
  {"name":"Fissure","type":"Ground"},
  {"name":"Dig","type":"Ground"},
  {"name":"Toxic","type":"Poison"},
  {"name":"Confusion","type":"Psychic"},
  {"name":"Psychic","type":"Psychic"},
  {"name":"Hypnosis","type":"Psychic"},
  {"name":"Meditate","type":"Psychic"},
  {"name":"Agility","type":"Psychic"},
  {"name":"Quick Attack","type":"Normal"},
  {"name":"Rage","type":"Normal"},
  {"name":"Teleport","type":"Psychic"},
  {"name":"Night Shade","type":"Ghost"},
  {"name":"Mimic","type":"Normal"},
  {"name":"Screech","type":"Normal"},
  {"name":"Double Team","type":"Normal"},
  {"name":"Recover","type":"Normal"},
  {"name":"Harden","type":"Normal"},
  {"name":"Minimize","type":"Normal"},
  {"name":"Smokescreen","type":"Normal"},
  {"name":"Confuse Ray","type":"Ghost"},
  {"name":"Withdraw","type":"Water"},
  {"name":"Defense Curl","type":"Normal"},
  {"name":"Barrier","type":"Psychic"},
  {"name":"Light Screen","type":"Psychic"},
  {"name":"Haze","type":"Ice"},
  {"name":"Reflect","type":"Psychic"},
  {"name":"Focus Energy","type":"Normal"},
  {"name":"Bide","type":"Normal"},
  {"name":"Metronome","type":"Normal"},
  {"name":"Mirror Move","type":"Flying"},
  {"name":"Self-Destruct","type":"Normal"},
  {"name":"Egg Bomb","type":"Normal"},
  {"name":"Lick","type":"Ghost"},
  {"name":"Smog","type":"Poison"},
  {"name":"Sludge","type":"Poison"},
  {"name":"Bone Club","type":"Ground"},
  {"name":"Fire Blast","type":"Fire"},
  {"name":"Waterfall","type":"Water"},
  {"name":"Clamp","type":"Water"},
  {"name":"Swift","type":"Normal"},
  {"name":"Skull Bash","type":"Normal"},
  {"name":"Spike Cannon","type":"Normal"},
  {"name":"Constrict","type":"Normal"},
  {"name":"Amnesia","type":"Psychic"},
  {"name":"Kinesis","type":"Psychic"},
  {"name":"Soft-Boiled","type":"Normal"},
  {"name":"High Jump Kick","type":"Fighting"}
]